<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>浅谈JS中的回调，事件，异步回调，和错误捕捉</title>
        <meta name="viewport" content="width=device-width">

        <!-- syntax highlighting CSS -->
        <link rel="stylesheet" href="/google_reader/css/syntax.css">

        <!-- Custom CSS -->
        <link rel="stylesheet" href="/google_reader/css/main.css">

    </head>
    <body>

        <div class="container">
          <div class="site">
            <div class="header">
              <h1 class="title"><a href="/google_reader/">Google Reader</a></h1>
              <a class="extra" href="/google_reader/">home</a>
            </div>

                <h2>浅谈JS中的回调，事件，异步回调，和错误捕捉</h2>
<p class="meta">2012-09-19 10:42</p>

<div class="post">
<h2>浅谈JS中的回调，事件，异步回调，和错误捕捉</h2>

<h3>by admin</h3>

<h3>at 2012-09-19 02:42:39</h3>

<h3>original <a href="http://item.feedsky.com/~feedsky/helloJavaScript/~8514355/703064731/6618683/1/item.html">http://item.feedsky.com/~feedsky/helloJavaScript/~8514355/703064731/6618683/1/item.html</a></h3>

<p></p>


<div>
<h1><a name="浅谈js中的回调_异步回调_和错误捕捉">浅谈JS中的回调，异步回调，和错误捕捉。</a></h1>
<div>
<p>关于NodeJS的种种就不介绍和吐槽了，我的了解也不是非常多，正在学习中。
</p>
<p>
这里就说说JS中的回调和错误捕捉。
</p>
</div>
<h2><a name="回调">回调</a></h2>
<div>
<p>先从例子开始吧。
</p>
<pre><span>/////////////////////</span>
<span>var</span> example_2=<span>function</span><span>(</span>callback<span>)</span><span>{</span>
    callback<span>(</span><span>)</span>;
<span>}</span>
<span>try</span><span>{</span>
    example_2<span>(</span><span>function</span><span>(</span><span>)</span><span>{</span>
        <span>throw</span> <span>new</span> Error<span>(</span><span>&quot;callback function&#39;s outer error&quot;</span><span>)</span>
    <span>}</span><span>)</span>;
<span>}</span><span>catch</span><span>(</span>e<span>)</span><span>{</span>
    console.<span>log</span><span>(</span>e<span>)</span>
<span>}</span></pre>
<p>
上图演示了基本的回调方法和外层错误捕捉，所谓回调，其实就是在方法的参数内传入另一个方法，在执行到一定时间的时候，执行回调方法。
</p>
<p>
上面演示的回调方法里有一句throw error，会抛出一个异常，然后我们用try catch 在外层进行捕捉，最后可以发现错误被捕捉，不会导致程序出错，并输出错误信息。
</p>
<pre>
Error:callback function&#39;s outer error
</pre>
</div>
<h2><a name="事件">事件</a></h2>
<div>
<p>事件其实就是一种被打扁的回调，从语义上来理解，其实也是一种回调，代码的执行都是同步阻塞。你绑定一个事件，其实就是增加了一个回调，到了要调用的时候会去调用。
</p>
<p>
事件的好处是可以把回调的代码打扁平。（其实回调也可以？）
</p>
<p>
例如：
</p>
<pre><span>var</span> test=<span>new</span> <span>***</span><span>(</span><span>)</span>
test.<span>on</span><span>(</span><span>&quot;init&quot;</span>,<span>function</span><span>(</span><span>)</span><span>{</span>
   <span>this</span>.<span>fire</span><span>(</span><span>&quot;render&quot;</span><span>)</span>;
<span>}</span><span>)</span>;
test.<span>on</span><span>(</span><span>&quot;render&quot;</span>,<span>function</span><span>(</span><span>)</span><span>{</span>
   <span>//....do other things</span>
<span>}</span><span>)</span>;</pre>
<p>
类似链式操作，但是操作仍然是串行的。
</p>
<p>
回调平铺：
</p>
<pre><span>**</span>.<span>proptype</span>.<span>init</span>=<span>function</span><span>(</span>callback<span>)</span><span>{</span>
   callback.<span>call</span><span>(</span><span>this</span><span>)</span>;
<span>}</span>
<span>var</span> test=<span>new</span> <span>**</span><span>(</span><span>)</span>;
<span>var</span> render_callback=<span>function</span><span>(</span><span>)</span><span>{</span>
    <span>//....</span>
<span>}</span>
<span>var</span> init_callback=<span>function</span><span>(</span><span>)</span><span>{</span>
    <span>this</span>.<span>render</span><span>(</span>render_callback<span>)</span>;
<span>}</span>
test.<span>init</span><span>(</span>init_callback<span>)</span></pre>
<p>
看起来好像完全不是平铺，仍然是嵌套，只是改了个写法而已，其实基于事件的实现之所以看不到这种过程，是因为都封装进了事件处理器。其实从原理上来说都是一个鸟样。
</p>
<p>总的来说，基于事件的设计可以承载更多状态而不会显得混乱，代码更扁平（更多处理是放在事件处理器中）。而基于回调的设计，状态简单，大概只有成功失败两种状态，一个回调即可搞定，在参数中体现失败信息即可。
</p>
<p>所以从根本上来说，二者并无差。特别是从错误捕捉方面来说。
</p>
<p>
看个真实可运行的例子吧，用的是NodeJS自带的事件处理器。</p>
<pre><span>var</span> util=require<span>(</span><span>'util'</span><span>)</span>
util.<span>mix</span>=<span>function</span><span>(</span>target,source<span>)</span><span>{</span>
    <span>for</span><span>(</span><span>var</span> i <span>in</span> source<span>)</span><span>{</span>
        target<span>[</span>i<span>]</span>=source<span>[</span>i<span>]</span>
    <span>}</span>
<span>}</span>
<span>var</span> events=require<span>(</span><span>&quot;events&quot;</span><span>)</span>
<span>var</span> example_10=<span>function</span><span>(</span><span>)</span><span>{</span>
    events.<span>EventEmitter</span>.<span>call</span><span>(</span><span>this</span><span>)</span>;
<span>}</span>
util.<span>inherits</span><span>(</span>example_10, events.<span>EventEmitter</span><span>)</span>;
util.<span>mix</span><span>(</span>example_10.<span>prototype</span>, <span>{</span>
    init:<span>function</span><span>(</span><span>)</span><span>{</span>
        <span>this</span>.<span>emit</span><span>(</span><span>&quot;init&quot;</span><span>)</span>
    <span>}</span>
<span>}</span><span>)</span>;
<span>var</span> ex=<span>new</span> example_10<span>(</span><span>)</span>;
ex.<span>on</span><span>(</span><span>&quot;init&quot;</span>,<span>function</span><span>(</span><span>)</span><span>{</span>
    <span>throw</span> <span>new</span> Error<span>(</span><span>&quot;event callback error&quot;</span><span>)</span>
<span>}</span><span>)</span>
<span>try</span><span>{</span>
    ex.<span>init</span><span>(</span><span>)</span>;
<span>}</span><span>catch</span><span>(</span>e<span>)</span><span>{</span>
    console.<span>log</span><span>(</span>e<span>)</span>
<span>}</span></pre>
<p>执行结果：</p>
<pre>
[Error:event callback error] //正常捕捉到错误，跟回调一个结果。
</pre>
</div>
<h2><a name="异步">异步</a></h2>
<div>
<p>
很多对js不了解的同学容易把这些概念搞混，异步跟回调还有事件，其实并木有什么本质联系。
</p>
<p>
在JS中的异步，主要是IO的异步，不管是NodeJS还是浏览器端JS。
</p>
<p>
浏览器端JS主要的异步行为是远程请求，workers，socket等，NodeJS中在此基础上增加一些例如对本地文件的操作，还有操作数据库（其实也是socket）等。
</p>
<p>
这些操作中，大部分都设计成事件机制的，但像对本地文件的操作，和某些框架的封装（例如mysql)因为状态大多只有两个，都被设计成基于回调的。
</p>
<p>
不过上面讨论过了，不管是事件还是回调，原理都一样。所以这里只讨论回调。
</p>
<p>
看个代码（NodeJS）：
</p>
<pre><span>var</span> Client = require<span>(</span><span>'mysql'</span><span>)</span>.<span>Client</span>;
<span>var</span> client = <span>new</span> Client<span>(</span><span>)</span>;
client.<span>user</span> =<span>&quot;root&quot;</span>;
client.<span>password</span> =<span>&quot;&quot;</span>;
client.<span>query</span><span>(</span><span>'USE test'</span><span>)</span>;
<span>try</span><span>{</span>
    client.<span>query</span><span>(</span>
        <span>'SELECT * FROM t where id=1'</span>,
        <span>function</span><span>(</span>err, results, fields<span>)</span> <span>{</span>
          <span>throw</span> <span>new</span> Error<span>(</span><span>&quot;asyn callback function&#39;s error&quot;</span><span>)</span>
        <span>}</span><span>)</span>;
<span>}</span><span>catch</span><span>(</span>e<span>)</span><span>{</span>
    console.<span>log</span><span>(</span>e<span>)</span>
<span>}</span></pre>
<p>
运行结果是神马呢？呵呵，这个应用会崩溃，提示throw error导致应用出错，也就是说try catch 木有捕捉到错误。
</p>
<p>
同样是回调，为啥捕捉不到捏，这就是异步回调了，JS中异步回调，因为真正的异步，已经跳出当前代码执行的顺序了，回调是由异步线程来负责监视和执行的。等回调被触发的时候，已经脱离了之前代码的trycatch的作用范围。深层次的机理，有兴趣可以去研究，这里说的都是表象。
</p>
<p>
可见，异步回调的代码必须在里面做捕捉，外面的捕捉捕捉不到异步回调代码里的报错。
</p>
<pre><span>var</span> Client = require<span>(</span><span>'mysql'</span><span>)</span>.<span>Client</span>;
<span>var</span> client = <span>new</span> Client<span>(</span><span>)</span>;
client.<span>user</span> =<span>&quot;root&quot;</span>;
client.<span>password</span> =<span>&quot;&quot;</span>;
client.<span>query</span><span>(</span><span>'USE test'</span><span>)</span>;
client.<span>query</span><span>(</span>
        <span>'SELECT * FROM t where id=1'</span>,
        <span>function</span><span>(</span>err, results, fields<span>)</span> <span>{</span>
          <span>try</span><span>{</span>
          <span>throw</span> <span>new</span> Error<span>(</span><span>&quot;asyn callback function&#39;s error&quot;</span><span>)</span>
          <span>}</span><span>catch</span><span>(</span>e<span>)</span><span>{</span>
 
          <span>}</span>
    <span>}</span><span>)</span>;</pre>
<p>其他的异步回调的处理也类似。
</p>
</div>
<h2><a name="其他">其他</a></h2>
<div>
<p>NodeJS比较让人烦的地方 就是回调方法的嵌套，很容易让代码变得层次很深，同时异步回调的错误又不能在外层捕捉，需要在每次回调的时候做处理，二者揉到一起，代码就更纷繁乱套了。
</p>
<p>
一般的解决方案就是把代码用事件平铺，可以用NodeJS自带的事件处理器平铺，也可以用第三方的库来做事件处理器，例如eventproxy之类的。
</p>
<p>
还有一些其他情况的错误捕捉，也许我们也该一起玩玩：
</p>
<pre><span>/////////</span>
<span>var</span> example_3=<span>function</span><span>(</span>callback<span>)</span><span>{</span>
    setTimeout<span>(</span><span>function</span><span>(</span><span>)</span><span>{</span>
        callback<span>(</span><span>)</span>;
    <span>}</span>,<span>100</span><span>)</span>
<span>}</span>
<span>try</span><span>{</span>
    example_3<span>(</span><span>function</span><span>(</span><span>)</span><span>{</span>
         <span>throw</span> <span>new</span> Error<span>(</span><span>&quot;callback function&#39;s settimeout error&quot;</span><span>)</span>
        <span>}</span><span>)</span>;
<span>}</span><span>catch</span><span>(</span>e<span>)</span><span>{</span>
    console.<span>log</span><span>(</span>e<span>)</span>
<span>}</span></pre>
<p>
setTimeout也是真异步，定时由单独的线程维护，所以处理起来也算是异步的，上述的结果跟异步回调的结果一样，需要内部捕捉错误。
</p>
<pre><span>var</span> example_3=<span>function</span><span>(</span>callback<span>)</span><span>{</span>
    <span>eval</span><span>(</span><span>&quot;(callback())&quot;</span><span>)</span>;
<span>}</span>
<span>try</span><span>{</span>
    example_3<span>(</span><span>function</span><span>(</span><span>)</span><span>{</span>
        <span>throw</span> <span>new</span> Error<span>(</span><span>&quot;callback function&#39;s eval error&quot;</span><span>)</span>
    <span>}</span><span>)</span>;
<span>}</span><span>catch</span><span>(</span>e<span>)</span><span>{</span>
    console.<span>log</span><span>(</span>e<span>)</span>
<span>}</span></pre>
<p>eval呢，上述的运行结果是正常的，表明其处理是同步的。具体细节就不深入了，对这些了解不多。
</p>
<p>
还有其他情况可以自己去实验一下，加深一下对try catch的理解。
</p>
<p>
错误处理在前端来说，重要性并不突出，因为前端可以约定限制，不需要考虑太多情况，但是后端因为各种依赖，很容易出现异常，需要在一些关键地方做一下处理，而且调试时候也更依赖throw error等工具，重要性不言而喻，所以理解错误捕捉在不同的情况下是如何工作滴是很重要滴。
</p>
<p>
thanks for reading。
</p>
</div>
</div>


<p></p>


<p><img src="http://www1.feedsky.com/t1/703064731/helloJavaScript/feedsky/s.gif?r=http://item.feedsky.com/~feedsky/helloJavaScript/~8514355/703064731/6618683/1/item.html" border="0" height="0" width="0"></p>

</div>


            <div class="footer">
              <div class="contact">
                <p>
                  Your Name<br />
                  What You Are<br />
                  your@email.com
                </p>
              </div>
              <div class="contact">
                <p>
                  <a href="http://github.com/lyuehh/">github.com/lyuehh</a><br />
                  <a href="http://twitter.com/lyuehh/">twitter.com/lyuehh</a><br />
                </p>
              </div>
            </div>
          </div>
        </div> <!-- /container -->

    </body>
</html>
